define pdns::recursor (
	$aaaa_additional_processing=false,
	$allow_from=false,
	$allow_from_file=false,
	$auth_can_lower_ttl=false,
	$auth_zones=false,
	$chroot=false,
	$client_tcp_timeout=false,
	$config_dir=false,
	$daemon=false,
	$delegatoin_only=false,
	$disable_packetcache=false,
	$disable_dns=false,
	$disable_edns_ping=false,
	$dont_query=false,
	$entropy_source=false,
	$etc_hosts_file=false,
	$export_etc_hosts=false,
	$forward_zones=false,
	$forward_zones_file=false,
	$forward_zones_recurse=false,
	$hint_file=false,
	$ignore_rd_bit=false,
	$log_common_errors=false,
	$logging_facility=false,
	$lua_dns_script=false,
	$max_cache_entries=false,
	$max_cache_ttl=false,
	$max_mthreads=false,
	$max_negative_ttl=false,
	$max_packetcache_entries=false,
	$max_tcp_clients=false,
	$max_tcp_per_client=false,
	$network_timeout=false,
	$no_shuffle=false,
	$packetcache_servfail_ttl=false,
	$packetcache_ttl=false,
	$pdns_distributes_queries=false,
	$processes=false,
	$query_local_address=false,
	$query_local_address6=false,
	$quiet=false,
	$remotes_ringbuffer_entries=false,
	$serve_rfc1918=false,
	$server_id=false,
	$setgid=false,
	$setuid=false,
	$single_socket=false,
	$soa_minimum_ttl=false,
	$soa_serial_offset=false,
	$socket_dir=false,
	$socket_group=false,
	$socket_mode=false,
	$socket_owner=false,
	$spoof_nearmiss_max=false,
	$stack_size=false,
	$threads=false,
	$trace=false,
	$version_string=false) {

        package { 'pdns-recursor':
                 ensure => installed,
        }
        service { 'pdns-recursor':
                ensure => running,
                enable => true,
                hasrestart => true,
        }	
}
